### ISSUE TITLE
## An error occurred while getting inventory: Error: HTTP error 404 

### ISSUE THREAD

**Issue by ItzThatKidBrian** [GGrandma/Steam-Card-Bot-v3#2]
Keep getting this
## An error occurred while getting inventory: Error: HTTP error 404
when ever someone tries to buy or sell.

**Comment by GGrandma** [comment]
@ItzThatKidBrian I was getting that same error to, I fixed it by re downloading all files. I'm thinking though if you just try starting the bot again it should work now.

**Comment by ItzThatKidBrian** [comment]
Yeah i'm trying that now... I tell you if it works in a sec.

**Comment by ItzThatKidBrian** [comment]
@GGrandma Still doesn't seem to be working...

Config:
![capture](https://user-images.githubusercontent.com/28121589/32673080-a8984fcc-c61b-11e7-9da4-5eed68c3d323.PNG)

**Comment by GGrandma** [comment]
@ItzThatKidBrian If you can get that error again please do, please send the entire error. Also while logged into the bot try viewing someones inventory

**Comment by ItzThatKidBrian** [comment]
@GGrandma looking at inventories works fine when logged into the bot.
console log:
![capture](https://user-images.githubusercontent.com/28121589/32673380-027325c0-c61d-11e7-9139-18a801a4da60.PNG)

**Comment by GGrandma** [comment]
@ItzThatKidBrian I think the cause is on your side, the only thing I can think to do is take the bot offline, wait 10-15 min then put it back up and try again. When I had this problem im not sure what I did that fixed it. Sorry there isnt much I can do.

**Comment by ItzThatKidBrian** [comment]
Alright ill just try again tomorrow. Thanks for trying appreciate it ♥

**Comment by GGrandma** [comment]
@ItzThatKidBrian while I was working more on the bot today after restarting the bot over and over I got that same error, after waiting 5+ min it just went away. I'm thinking steam is just giving you a temp ip ban for to much traffic.

**Comment by ItzThatKidBrian** [comment]
@GGrandma  Hmmmm... interesting.... I'll try a VPN maybe? I've been constantly working on it so ill try again tomorrow.

**Comment by AndrewRAN** [comment]
Same thing hapened with me. @ItzThatKidBrian did you fix that problem?

**Comment by ItzThatKidBrian** [comment]
@AndrewRAN Nope... I feel like it has something to do with the code now, ill check it out.

**Comment by ItzThatKidBrian** [comment]
@GGrandma @AndrewRAN I feel like there is a problem around this area...
![capture](https://user-images.githubusercontent.com/28121589/32692664-2cceab46-c6ea-11e7-99fa-cab0c45754fd.PNG)

**Comment by GGrandma** [comment]
@ItzThatKidBrian it could be with the code, but if it was it should happen everytime. For me as said before its very on and off.

**Comment by ItzThatKidBrian** [comment]
For me it was every time

**Comment by GGrandma** [comment]
Was? is it working now?

**Comment by ItzThatKidBrian** [comment]
Ill try re-downloading it.

**Comment by ItzThatKidBrian** [comment]
wait wtf

**Comment by GGrandma** [comment]
xd

**Comment by ItzThatKidBrian** [comment]
oh ok lol i accidentally closed it

**Comment by GGrandma** [comment]
Ok, im thinking the problem is with the bots cookies expiring and bot not renewing them.

**Comment by ItzThatKidBrian** [comment]
Like the web session?

**Comment by GGrandma** [comment]
Yes

**Comment by ItzThatKidBrian** [comment]
It might be... but I know half of the things that u do xD

**Comment by GGrandma** [comment]
@ItzThatKidBrian Do you have any csgo items in your inventory, or are you VAC banned? Any csgo items means, any not just keys. I belive either not having a csgo inventory or being vac banned may be the cause. Because buying with csgo keys for me dosnt work but buying with tf or pubg keys works.

**Comment by ItzThatKidBrian** [comment]
@GGrandma The bot doesn't have any csgo items but only keys and cards and neither of us have a VAC ban.

**Comment by GGrandma** [comment]
@ItzThatKidBrian very confused, !buyany work. !buy dosnt work.

**Comment by ItzThatKidBrian** [comment]
Interesting... If you can fix these problems I will pay 15$ for the "Full version" with no problem

**Comment by xman116** [comment]
Having the same problems. Any solution yet?

**Comment by GGrandma** [comment]
I am very embarrassed at what was causing the error, forgot to add KEYSFROMGAME to the config. This is now fixed in the most recent commit. @ItzThatKidBrian @AndrewRAN @xman116

**Comment by GGrandma** [comment]
Are you still intrested in the “full/paid” version? :)

**Comment by ItzThatKidBrian** [comment]
@GGrandma I added u on discord, add me back at ItzThatKidBrian#8055

**Comment by AndrewRAN** [comment]
@GGrandma what do I do now? Redownload the bot?

**Comment by GGrandma** [comment]
@AndrewRAN yes just save your config file
